# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fyrmesh.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/fyrmesh.proto',
  package='main',
  syntax='proto3',
  serialized_options=b'Z\006/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13proto/fyrmesh.proto\x12\x04main\"z\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\x12-\n\x08metadata\x18\x02 \x03(\x0b\x32\x1b.main.Message.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"-\n\x0b\x41\x63knowledge\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"/\n\nMeshStatus\x12\x0e\n\x06meshID\x18\x01 \x01(\t\x12\x11\n\tconnected\x18\x02 \x01(\x08\"F\n\x0cInterfaceLog\x12\x11\n\tlogsource\x18\x01 \x01(\t\x12\x0f\n\x07logtime\x18\x02 \x01(\t\x12\x12\n\nlogmessage\x18\x03 \x01(\t\"\x8c\x01\n\x10InterfaceCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x36\n\x08metadata\x18\x02 \x03(\x0b\x32$.main.InterfaceCommand.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32p\n\tInterface\x12-\n\x04Read\x12\r.main.Message\x1a\x12.main.InterfaceLog\"\x00\x30\x01\x12\x34\n\x05Write\x12\x16.main.InterfaceCommand\x1a\x11.main.Acknowledge\"\x00\x32\xc6\x01\n\x0cOrchestrator\x12+\n\x06Status\x12\r.main.Message\x1a\x10.main.MeshStatus\"\x00\x12\x30\n\nConnection\x12\r.main.Message\x1a\x11.main.Acknowledge\"\x00\x12+\n\x07Observe\x12\r.main.Message\x1a\r.main.Message\"\x00\x30\x01\x12*\n\x04Ping\x12\r.main.Message\x1a\x11.main.Acknowledge\"\x00\x42\x08Z\x06/protob\x06proto3'
)




_MESSAGE_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='main.Message.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='main.Message.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='main.Message.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=151,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='main.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='main.Message.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='main.Message.metadata', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=151,
)


_ACKNOWLEDGE = _descriptor.Descriptor(
  name='Acknowledge',
  full_name='main.Acknowledge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='main.Acknowledge.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='main.Acknowledge.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=198,
)


_MESHSTATUS = _descriptor.Descriptor(
  name='MeshStatus',
  full_name='main.MeshStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='meshID', full_name='main.MeshStatus.meshID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connected', full_name='main.MeshStatus.connected', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=247,
)


_INTERFACELOG = _descriptor.Descriptor(
  name='InterfaceLog',
  full_name='main.InterfaceLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='logsource', full_name='main.InterfaceLog.logsource', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logtime', full_name='main.InterfaceLog.logtime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logmessage', full_name='main.InterfaceLog.logmessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=319,
)


_INTERFACECOMMAND_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='main.InterfaceCommand.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='main.InterfaceCommand.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='main.InterfaceCommand.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=151,
)

_INTERFACECOMMAND = _descriptor.Descriptor(
  name='InterfaceCommand',
  full_name='main.InterfaceCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='main.InterfaceCommand.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='main.InterfaceCommand.metadata', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_INTERFACECOMMAND_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=462,
)

_MESSAGE_METADATAENTRY.containing_type = _MESSAGE
_MESSAGE.fields_by_name['metadata'].message_type = _MESSAGE_METADATAENTRY
_INTERFACECOMMAND_METADATAENTRY.containing_type = _INTERFACECOMMAND
_INTERFACECOMMAND.fields_by_name['metadata'].message_type = _INTERFACECOMMAND_METADATAENTRY
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Acknowledge'] = _ACKNOWLEDGE
DESCRIPTOR.message_types_by_name['MeshStatus'] = _MESHSTATUS
DESCRIPTOR.message_types_by_name['InterfaceLog'] = _INTERFACELOG
DESCRIPTOR.message_types_by_name['InterfaceCommand'] = _INTERFACECOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGE_METADATAENTRY,
    '__module__' : 'proto.fyrmesh_pb2'
    # @@protoc_insertion_point(class_scope:main.Message.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'proto.fyrmesh_pb2'
  # @@protoc_insertion_point(class_scope:main.Message)
  })
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.MetadataEntry)

Acknowledge = _reflection.GeneratedProtocolMessageType('Acknowledge', (_message.Message,), {
  'DESCRIPTOR' : _ACKNOWLEDGE,
  '__module__' : 'proto.fyrmesh_pb2'
  # @@protoc_insertion_point(class_scope:main.Acknowledge)
  })
_sym_db.RegisterMessage(Acknowledge)

MeshStatus = _reflection.GeneratedProtocolMessageType('MeshStatus', (_message.Message,), {
  'DESCRIPTOR' : _MESHSTATUS,
  '__module__' : 'proto.fyrmesh_pb2'
  # @@protoc_insertion_point(class_scope:main.MeshStatus)
  })
_sym_db.RegisterMessage(MeshStatus)

InterfaceLog = _reflection.GeneratedProtocolMessageType('InterfaceLog', (_message.Message,), {
  'DESCRIPTOR' : _INTERFACELOG,
  '__module__' : 'proto.fyrmesh_pb2'
  # @@protoc_insertion_point(class_scope:main.InterfaceLog)
  })
_sym_db.RegisterMessage(InterfaceLog)

InterfaceCommand = _reflection.GeneratedProtocolMessageType('InterfaceCommand', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _INTERFACECOMMAND_METADATAENTRY,
    '__module__' : 'proto.fyrmesh_pb2'
    # @@protoc_insertion_point(class_scope:main.InterfaceCommand.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _INTERFACECOMMAND,
  '__module__' : 'proto.fyrmesh_pb2'
  # @@protoc_insertion_point(class_scope:main.InterfaceCommand)
  })
_sym_db.RegisterMessage(InterfaceCommand)
_sym_db.RegisterMessage(InterfaceCommand.MetadataEntry)


DESCRIPTOR._options = None
_MESSAGE_METADATAENTRY._options = None
_INTERFACECOMMAND_METADATAENTRY._options = None

_INTERFACE = _descriptor.ServiceDescriptor(
  name='Interface',
  full_name='main.Interface',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=464,
  serialized_end=576,
  methods=[
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='main.Interface.Read',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_INTERFACELOG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='main.Interface.Write',
    index=1,
    containing_service=None,
    input_type=_INTERFACECOMMAND,
    output_type=_ACKNOWLEDGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INTERFACE)

DESCRIPTOR.services_by_name['Interface'] = _INTERFACE


_ORCHESTRATOR = _descriptor.ServiceDescriptor(
  name='Orchestrator',
  full_name='main.Orchestrator',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=579,
  serialized_end=777,
  methods=[
  _descriptor.MethodDescriptor(
    name='Status',
    full_name='main.Orchestrator.Status',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESHSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Connection',
    full_name='main.Orchestrator.Connection',
    index=1,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_ACKNOWLEDGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Observe',
    full_name='main.Orchestrator.Observe',
    index=2,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='main.Orchestrator.Ping',
    index=3,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_ACKNOWLEDGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORCHESTRATOR)

DESCRIPTOR.services_by_name['Orchestrator'] = _ORCHESTRATOR

# @@protoc_insertion_point(module_scope)
